In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

import matplotlib.pyplot as plt
import matplotlib as mpl
from scipy import stats
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from datetime import datetime
import statsmodels.api as sm
from pandas.plotting import lag_plot
from pmdarima.arima import auto_arima
import warnings
warnings.filterwarnings("ignore")
import pmdarima as pm
import os
from statsmodels.tsa.arima.model import ARIMA
directory = "./data1/"
list_rs2 = []
df = pd.DataFrame()
df_results = pd.DataFrame(columns=["Name", "RMSE"])
#df = pd.read_csv(f"./data1/",parse_dates=['nav_date'])
df = pd.read_csv(f"./data1/"+ "M0090_2561_SSF" +".csv",parse_dates=['nav_date'])
df['nav_date'] = pd.to_datetime(df['nav_date'])
monthly_avg = df.set_index('nav_date').resample('M').mean()
df = pd.DataFrame(monthly_avg["last_val"])
df = df.dropna()
#df_RS2 = pd.concat([df_RS2, df_Rs2_temp])
#df_RS2 = df_RS2._append(df_Rs2_temp)
num = 6
train_size = int(len(df)-num)
test_size = len(df) - train_size
train_data = df.iloc[:train_size]
test_data = df.iloc[train_size:]
scaler = MinMaxScaler(feature_range = (0,1))
df_scaled = scaler.fit_transform(df)
train_scaled = df_scaled[:train_size]
test_scaled = df_scaled[train_size:]
auto_arima = pm.auto_arima(train_scaled, stepwise=False, seasonal=True)
forecastnum = 12
forecast_test_auto = auto_arima.predict(n_periods=len(test_scaled)+forecastnum)
forcastnew_data = scaler.inverse_transform(forecast_test_auto.reshape(-1,1))
forcastnew_data_back6months = forcastnew_data[:-forecastnum]
forcastnew_data_1year = forcastnew_data[-forecastnum:] 
RMSE_error = mean_squared_error(test_data, forcastnew_data_back6months)
#df_results = df_results._append({"Name": filename, "RMSE": RMSE_error}, ignore_index=True)
print('Testing Mean Squared Error is {}'.format(RMSE_error))
from datetime import datetime, timedelta
import calendar
current_date = datetime.now()
current_month = datetime.now().month
months = [(calendar.month_name[(current_month + i - 1) % 12 + 1]) for i in range(12)]
Months12 = pd.DataFrame({'Month': months})
Months12["income"] = 10000
Months12['expense'] = np.random.randint(1000, 5001, size=len(Months12))
Months12['invesment'] = np.random.randint(1000, 5001, size=len(Months12))
Months12['remaining'] = Months12["income"] - Months12['expense'] - Months12['invesment']
Months12["Stockprice_predicted(Months)"] = forcastnew_data_1year
Months12['units'] = Months12["income"]/Months12["Stockprice_predicted(Months)"]
Months12["sum_units"] = Months12['units'].cumsum()
Months12["Sum_Values_Monthly"] = Months12["sum_units"] * Months12["Stockprice_predicted(Months)"]
Months12["income_sum"] = Months12["income"].cumsum()
Months12["Growth_rate_percent"] = ((Months12["Sum_Values_Monthly"] - Months12["income_sum"])/Months12["income_sum"])*100
Months12["Profit"] = Months12["Sum_Values_Monthly"]-Months12["income_sum"]
Months12

C:\Users\User\AppData\Local\Temp\ipykernel_20492\2835060617.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

Testing Mean Squared Error is 0.051348906518079634

,Month,income,expense,invesment,remaining,Stockprice_predicted(Months),units,sum_units,Sum_Values_Monthly,income_sum,Growth_rate_percent,Profit
0,February,10000,1872,1518,6610,9.546571,1047.496486,1047.496486,10000.000000,10000,0.000000,0.000000
1,March,10000,3123,3779,3098,9.525160,1049.851165,2097.347651,19977.571314,20000,-0.112143,-22.428686
2,April,10000,3580,2120,4300,9.508583,1051.681404,3149.029055,29942.804375,30000,-0.190652,-57.195625
3,May,10000,4849,3585,1566,9.493195,1053.386147,4202.415203,39894.346559,40000,-0.264134,-105.653441
4,June,10000,2414,4250,3336,9.480566,1054.789357,5257.204560,49841.274215,50000,-0.317452,-158.725785
5,July,10000,2803,2934,4263,9.469306,1056.043578,6313.248138,59782.079737,60000,-0.363200,-217.920263
6,August,10000,4152,2896,2952,9.459815,1057.103163,7370.351301,69722.157307,70000,-0.396918,-277.842693
7,September,10000,1124,1211,7665,9.451506,1058.032491,8428.383792,79660.916484,80000,-0.423854,-339.083516
8,October,10000,3535,1467,4998,9.444415,1058.826828,9487.210620,89601.154470,90000,-0.443162,-398.845530
9,November,10000,4214,2447,3339,9.438259,1059.517420,10546.728040,99542.752600,100000,-0.457247,-457.247400
10,December,10000,4962,4030,1008,9.432977,1060.110759,11606.838799,109487.038958,110000,-0.466328,-512.961042
11,January,10000,1202,1952,6846,9.428408,1060.624473,12667.463272,119434.008871,120000,-0.471659,-565.991129