Header Api keys

In [5]:
pip install requests

Collecting requestsNote: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: C:\Users\User\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ---------------------------------------- 0.0/62.6 kB ? eta -:--:--
     ------------------- -------------------- 30.7/62.6 kB 1.4 MB/s eta 0:00:01
     -------------------------------------  61.4/62.6 kB 825.8 kB/s eta 0:00:01
     -------------------------------------- 62.6/62.6 kB 670.9 kB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
     ---------------------------------------- 0.0/163.8 kB ? eta -:--:--
     -------------- ------------------------ 61.4/163.8 kB 1.7 MB/s eta 0:00:01
     -------------------------- ----------- 112.6/163.8 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 163.8/163.8 kB 1.6 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
     ---------------------------------------- 0.0/100.3 kB ? eta -:--:--
     -------------------------------------- 100.3/100.3 kB 2.9 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.6-py3-none-any.whl (61 kB)
     ---------------------------------------- 0.0/61.6 kB ? eta -:--:--
     ---------------------------------------- 61.6/61.6 kB 1.1 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.2.0-py3-none-any.whl (120 kB)
     ---------------------------------------- 0.0/120.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/120.9 kB ? eta -:--:--
     --- ------------------------------------ 10.2/120.9 kB ? eta -:--:--
     ------------------ ------------------ 61.4/120.9 kB 825.8 kB/s eta 0:00:01
     -------------------------------------- 120.9/120.9 kB 1.4 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 idna-3.6 requests-2.31.0 urllib3-2.2.0

In [7]:
import requests
import json

import pandas as pd

headers1 = {
    # Request headers of fund daily info
    'Ocp-Apim-Subscription-Key': 'c1714d1753d5947f5b8f6f3cb67354d1d'
}

headers2 = {
    # Request headers of fund fact sheet
    'Ocp-Apim-Subscription-Key': '89cbe200e6ee4afca33f6e2122aa5e82'
}

ยิง API นำชื่อของแต่ละ บลจ.

In [8]:
response = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/amc',headers=headers2)
amc_name = json.loads(response.text)
df = pd.DataFrame(amc_name)
df

,unique_id,name_th,name_en,last_upd_date
0,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,KASIKORN ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
1,C0000000023,บริษัท หลักทรัพย์จัดการกองทุนเอ็มเอฟซี จำกัด (...,MFC ASSET MANAGEMENT PUBLIC COMPANY LIMITED,2024-02-02T07:05:13.913
2,C0000000124,บริษัท หลักทรัพย์จัดการกองทุนเมอร์ชั่น พาร์ทเน...,MERCHANT PARTNERS ASSET MANAGEMENT LIMITED,2024-02-02T07:05:13.913
3,C0000000182,บริษัท หลักทรัพย์จัดการกองทุนทหารไทย จำกัด,TMB ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
4,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,SCB ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
5,C0000000290,บริษัท หลักทรัพย์จัดการกองทุนอเบอร์ดีน (ประเทศ...,ABERDEEN ASSET MANAGEMENT (THAILAND) COMPANY L...,2024-02-02T07:05:13.913
6,C0000000324,บริษัท หลักทรัพย์จัดการกองทุนทิสโก้ จำกัด,TISCO ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
7,C0000000329,บริษัท หลักทรัพย์จัดการกองทุนรวมบัวหลวง จำกัด,BBL ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
8,C0000000460,บริษัท หลักทรัพย์จัดการกองทุนกรุงไทย จำกัด (มห...,KRUNG THAI ASSET MANAGEMENT PUBLIC COMPANY LIM...,2024-02-02T07:05:13.913
9,C0000000569,บริษัท หลักทรัพย์จัดการกองทุน วรรณ จำกัด,ONE ASSET MANAGEMENT LIMITED,2024-02-02T07:05:13.913
10,C0000000623,บริษัท หลักทรัพย์จัดการกองทุนยูโอบี (ประเทศไทย...,UOB ASSET MANAGEMENT (THAILAND) COMPANY LIMITED,2024-02-02T07:05:13.913
11,C0000000709,บริษัท หลักทรัพย์จัดการกองทุนกรุงศรี จำกัด,KRUNGSRI ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
12,C0000000714,บริษัท หลักทรัพย์จัดการกองทุนธนชาต จำกัด,THANACHART FUND MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
13,C0000003575,บริษัท หลักทรัพย์จัดการกองทุนสยาม ไนท์ ฟันด์ แ...,SIAM KNIGHT FUND MANAGEMENT SECURITIES COMPANY...,2024-02-02T07:05:13.913
14,C0000004884,บริษัท หลักทรัพย์จัดการกองทุนฟินันซ่า จำกัด,FINANSA ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
15,C0000005022,บริษัท หลักทรัพย์จัดการกองทุนแอสเซท พลัส จำกัด,ASSET PLUS FUND MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
16,C0000005025,บริษัท หลักทรัพย์จัดการกองทุนเกียรตินาคินภัทร ...,KIATNAKIN PHATRA ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
17,C0000005531,บริษัท หลักทรัพย์จัดการกองทุนพรินซิเพิล จำกัด,PRINCIPAL ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
18,C0000006099,บริษัท หลักทรัพย์จัดการกองทุนเอ็กซ์สปริง จำกัด,XSPRING ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
19,C0000006122,บริษัท หลักทรัพย์จัดการกองทุนรวมฟิลลิป จำกัด,PHILLIP ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
20,C0000006185,บริษัท หลักทรัพย์จัดการกองทุนเคดับบลิวไอ จำกัด,KWI ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
21,C0000006466,บริษัท หลักทรัพย์จัดการกองทุนเรนเนสซานซ์ จำกัด,RENAISSANCE FUND MANAGEMENT LIMITED,2024-02-02T07:05:13.913
22,C0000006646,บริษัท หลักทรัพย์จัดการกองทุนแลนด์ แอนด์ เฮ้าส...,LAND AND HOUSES FUND MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
23,C0000021747,บริษัท หลักทรัพย์จัดการกองทุนบางกอกแคปปิตอล จำกัด,BANGKOK CAPITAL ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
24,C0000024008,บริษัท หลักทรัพย์จัดการกองทุนทาลิส จำกัด,TALIS ASSET MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
25,C0000028866,บริษัท หลักทรัพย์จัดการกองทุนดาโอ จำกัด,DAOL INVESTMENT MANAGEMENT COMPANY LIMITED,2024-02-02T07:05:13.913
26,C0000031161,บริษัท หลักทรัพย์จัดการกองทุนเอไอเอ (ประเทศไทย...,AIA INVESTMENT MANAGEMENT (THAILAND) LIMITED,2024-02-02T07:05:13.913
27,C0000033081,บริษัท หลักทรัพย์จัดการกองทุนซาวาคามิ (ประเทศไ...,SAWAKAMI ASSET MANAGEMENT (THAILAND) COMPANY L...,2024-02-02T07:05:13.913
28,C0000033452,บริษัท หลักทรัพย์จัดการกองทุนอีสท์สปริง (ประเท...,EASTSPRING ASSET MANAGEMENT (THAILAND) COMPANY...,2024-02-02T07:05:13.913

Script ยิง API เก็บ risk_spectrum และ spec_code ของแต่ละ กองทุนภายใน บลจ. ที่เก็บไว้ตอนแรก

In [ ]:
import time
import csv
header = ['proj_id','risk_spectrum','spec_code']
for index, row in df.iterrows():
    list_risk = []
    response = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/amc/{row["unique_id"]}', headers = headers2)
    obj_dict = json.loads(response.text)
    filename = f'spec_suit/'+row["unique_id"]+'.csv'
    with open(filename, 'w',newline = '') as f_out:    
        f_out = csv.writer(f_out,quoting=csv.QUOTE_ALL)
        f_out.writerow(header)
        for x in obj_dict:
                suit_tmp = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/{x["proj_id"]}/suitability', headers=headers2)
                spec_tmp = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/{x["proj_id"]}/specification', headers=headers2)
                time.sleep(0.1)
                tmp_data = {}
                suit_json = {}
                spec_json = {}
                try:
                    # suit
                    suit_json = json.loads(suit_tmp.text)
                    tmp_data['proj_id'] = x['proj_id']
                    tmp_data['risk_spectrum'] = suit_json['risk_spectrum']
                except Exception as e1:
                    print(f"Error in Suit: {e1}")

                try:
                    # spec
                    spec_json = json.loads(spec_tmp.text)
                    tmp_data['proj_id'] = x['proj_id']
                    tmp_data['spec_code'] = ','.join(y['spec_code'] for y in spec_json)
                except Exception as e2:
                    print(f"Error in Spec: {e2}")
                if not tmp_data == {}:
                    f_out.writerow([tmp_data.get('proj_id'), tmp_data.get('risk_spectrum'), tmp_data.get('spec_code')])

Scipt ยิง API เก็บข้อมูลของ บลจ. SCB (C0000000239) เก็บ proj_id, risk_spectrum, spec_code, proj_retail_type

In [29]:
import time
import csv
from IPython.display import clear_output
header = ['proj_id','risk_spectrum','spec_code','proj_retail_type']
list_risk = []
response = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/amc/C0000000239', headers = headers2)
obj_dict = json.loads(response.text)
filename = f'SCB_amc_data/SCB_AMC_DATA.csv'
max = len(obj_dict)
with open(filename,'w',newline = '') as f_out:    
    f_out = csv.writer(f_out,quoting=csv.QUOTE_ALL)
    f_out.writerow(header)
    count = 1
    for x in obj_dict:
            suit_tmp = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/{x["proj_id"]}/suitability', headers=headers2)
            spec_tmp = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/{x["proj_id"]}/specification', headers=headers2)
            type_tmp = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/{x["proj_id"]}/project_type', headers=headers2)
            time.sleep(0.1)
            tmp_data = {}
            suit_json = {}
            spec_json = {}
            type_json = {}
            print(str(count)+' of '+str(max))
            try:
                # suit
                suit_json = json.loads(suit_tmp.text)
                tmp_data['proj_id'] = x['proj_id']
                tmp_data['risk_spectrum'] = suit_json['risk_spectrum']
            except Exception as e1:
                pass
            try:
                # spec
                spec_json = json.loads(spec_tmp.text)
                tmp_data['proj_id'] = x['proj_id']
                tmp_data['spec_code'] = ','.join(y['spec_code'] for y in spec_json)
            except Exception as e2:
                pass
            try:
                # type
                type_json = json.loads(type_tmp.text)
                tmp_data['proj_id'] = x['proj_id']
                tmp_data['proj_retail_type'] = type_json['proj_retail_type']
            except Exception as e3:
                pass
            if not tmp_data == {}:
                f_out.writerow([tmp_data.get('proj_id'), tmp_data.get('risk_spectrum'), tmp_data.get('spec_code'), tmp_data.get('proj_retail_type')])
            count+=1
            clear_output(wait=True)

2801 of 2801

Clean Data ลบ แถวที่เป็น NaN บน spec_code หรือ proj_retail_type

In [4]:
import pandas as pd
SCB_amc_data = pd.DataFrame(columns = ['proj_id','risk_spectrum','spec_code','amc','name_th','proj_retail_type'])
file = pd.read_csv(f'SCB_amc_data/SCB_AMC_DATA.csv')
file['amc'] =  'C0000000239'
file['name_th'] = 'บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด'
SCB_amc_data = pd.concat([SCB_amc_data,file])
SCB_amc_data_clean = SCB_amc_data.dropna(subset=['spec_code','proj_retail_type'])
SCB_amc_data_clean.drop(SCB_amc_data_clean[SCB_amc_data_clean['proj_retail_type'] != 'R'].index, inplace = True)
SCB_amc_data_clean

C:\Users\THIS-PC\AppData\Local\Temp\ipykernel_3852\2460296626.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  SCB_amc_data_clean.drop(SCB_amc_data_clean[SCB_amc_data_clean['proj_retail_type'] != 'R'].index, inplace = True)

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
12,M0003_2554,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
20,M0004_2564,NaN,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
25,M0005_2556,NaN,"FIF,SPF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
27,M0005_2558,NaN,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
30,M0005_2565,NaN,"FF,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
...,...,...,...,...,...,...
2762,M1086_2557,NaN,"FIF,SPF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2774,M1126_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2775,M1127_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2782,M1179_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2796,M1233_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

In [5]:
SCB_amc_data['risk_spectrum'].value_counts()

risk_spectrum
RS4    185
RS3      4
RS5      2
Name: count, dtype: int64

In [6]:
len(SCB_amc_data_clean)

1270

แบ่งกองทุน rmf_ssf กับที่ไม่ใช่ rmf_ssf ออกจากกันและใส่ใน Dataframe ใหม่

In [7]:
SCB_amc_rmf_ssf = SCB_amc_data_clean[SCB_amc_data_clean['spec_code'].str.contains('RMF', case=False, na=False) | SCB_amc_data_clean['spec_code'].str.contains('SSF', case=False, na=False)]
SCB_amc_no_rmf_ssf = SCB_amc_data_clean[~(SCB_amc_data_clean['spec_code'].str.contains('RMF', case=False, na=False) | SCB_amc_data_clean['spec_code'].str.contains('SSF', case=False, na=False))]

In [ ]:
SCB_amc_rmf_ssf = SCB_amc_rmf_ssf.reset_index()
SCB_amc_rmf_ssf = SCB_amc_rmf_ssf.drop(columns=['level_0','index'])
SCB_amc_rmf_ssf

In [46]:
SCB_amc_no_rmf_ssf

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
12,M0003_2554,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
20,M0004_2564,NaN,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
25,M0005_2556,NaN,"FIF,SPF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
35,M0006_2556,NaN,"FIF,SPF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
36,M0006_2558,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
...,...,...,...,...,...,...
2762,M1086_2557,NaN,"FIF,SPF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2774,M1126_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2775,M1127_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2782,M1179_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2796,M1233_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

ดึง Files pdf จาก API มาเก็บไว้บนเครื่อง

In [60]:
for index, row in SCB_amc_rmf_ssf.iterrows():
        response = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/{row["proj_id"]}/URLs',headers=headers2)
        res_text = json.loads(response.text)
        res_pdf = requests.get(res_text['url_factsheet'])
        with open(f"pdf_factsheet/{row['proj_id']}.pdf", 'wb') as pdf_file:
                pdf_file.write(res_pdf.content)

ใช้ pdfbox extract text ออกมาจากในแต่ละ File pdf

In [65]:
import pdfbox
p = pdfbox.PDFBox()
for index, row in SCB_amc_rmf_ssf.iterrows():
    try:
        p.extract_text(f'pdf_factsheet/{row["proj_id"]}.pdf')
    except Exception as e:
        print(e)

java.io.IOException: Error: End-of-File, expected line at offset 215
java.io.IOException: Error: End-of-File, expected line at offset 215
java.io.IOException: Error: End-of-File, expected line at offset 215

Scan files from pdf_factsheet folder to find all the files that have .txt extension

In [75]:
import os

folder_path = 'pdf_factsheet'
target_extension = '.txt'  
not_delete_list = []
file_names = [f for f in os.listdir(folder_path) if f.endswith(target_extension) and os.path.isfile(os.path.join(folder_path, f))]

for file_name in file_names:
    file_name = file_name.replace('.txt','')
    not_delete_list.append(file_name)

Delete all pdf files that wasn't on the list (from the io Exception above the txt files from specific pdf files cannot be extract by pdfbox)

In [78]:
import os

folder_path = 'pdf_factsheet'
all_files = os.listdir(folder_path)
for file_name in all_files:
    file_base_name, file_extension = os.path.splitext(file_name)
    if file_base_name not in not_delete_list and os.path.isfile(os.path.join(folder_path, file_name)):
        full_file_path = os.path.join(folder_path, file_name)
        try:
            os.remove(full_file_path)
            print(f"File {full_file_path} deleted successfully.")
        except FileNotFoundError:
            print(f"File {full_file_path} not found.")
        except Exception as e:
            print(f"Error deleting file {full_file_path}: {e}")

File pdf_factsheet\M0165_2564.pdf deleted successfully.
File pdf_factsheet\M0236_2554.pdf deleted successfully.
File pdf_factsheet\M0612_2558.pdf deleted successfully.

Filter out all the row that are not in the not_delete_list (have data)

In [79]:
SCB_amc_rmf_ssf_filter = SCB_amc_rmf_ssf[SCB_amc_rmf_ssf['proj_id'].isin(not_delete_list)]

In [80]:
SCB_amc_rmf_ssf_filter #this is the filtered version of amc consists only of RMF || SSF amc that doesn't have risk_spectrum yet but all are R proj retail type and from SCB

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,M0005_2558,NaN,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1,M0005_2565,NaN,"FF,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2,M0017_2565,NaN,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
3,M0049_2565,NaN,"FED,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
4,M0059_2564,NaN,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
...,...,...,...,...,...,...
92,M0856_2553,NaN,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
93,M0866_2554,NaN,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
94,M0874_2554,NaN,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
95,M0933_2554,NaN,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
96,M0935_2554,NaN,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

In [86]:
SCB_amc_rmf_ssf_filter_w_risk_spectrum = SCB_amc_rmf_ssf_filter

Scan all the extracted text files if it contains ": เสี่ยง" to find the according risk_spectrum and inplace the found value on 'risk_spectrum' column

In [96]:
import re
for index, row in SCB_amc_rmf_ssf_filter_w_risk_spectrum.iterrows():
    with open(f'pdf_factsheet/{row["proj_id"]}.txt', 'r',  encoding="utf8") as file:
        data = file.read()
        match = re.search(r'(\S+)\s*:\s*เสี่ยง', data)
        if match:
            number_before_string = match.group(1)
            SCB_amc_rmf_ssf_filter_w_risk_spectrum.at[index, 'risk_spectrum'] = number_before_string
        else:
            print("Pattern not found on "+ row["proj_id"])
SCB_amc_rmf_ssf_filter_w_risk_spectrum

Pattern not found on M0279_2561
Pattern not found on M0424_2562
Pattern not found on M0778_2554
Pattern not found on M0856_2553

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,M0005_2558,6,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1,M0005_2565,5,"FF,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2,M0017_2565,6,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
3,M0049_2565,6,"FED,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
4,M0059_2564,6,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
...,...,...,...,...,...,...
92,M0856_2553,NaN,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
93,M0866_2554,4,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
94,M0874_2554,5,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
95,M0933_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
96,M0935_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

Drop all NaN that the above logic cannot find the risk_spectrum of.

In [101]:
nan_rows = SCB_amc_rmf_ssf_filter_w_risk_spectrum[SCB_amc_rmf_ssf_filter_w_risk_spectrum.isna().any(axis=1)]
nan_rows

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
37,M0279_2561,NaN,"FF,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
55,M0424_2562,NaN,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
89,M0778_2554,NaN,"FED,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
92,M0856_2553,NaN,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

In [102]:
SCB_amc_rmf_ssf_filter_w_risk_spectrum_no_nan = SCB_amc_rmf_ssf_filter_w_risk_spectrum.dropna()
SCB_amc_rmf_ssf_filter_w_risk_spectrum_no_nan

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,M0005_2558,6,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1,M0005_2565,5,"FF,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2,M0017_2565,6,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
3,M0049_2565,6,"FED,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
4,M0059_2564,6,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
...,...,...,...,...,...,...
91,M0828_2554,5,"FF,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
93,M0866_2554,4,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
94,M0874_2554,5,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
95,M0933_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
96,M0935_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

Write to .csv file

In [106]:
SCB_amc_rmf_ssf_filter_w_risk_spectrum_no_nan.to_csv('SCB_amc_data/SCB_amc_rmf_ssf_filter_w_risk_spectrum_no_nan.csv', encoding='utf8')

In [109]:
SCB_amc_rmf_ssf_filter_w_risk_spectrum_no_nan['risk_spectrum'].value_counts()

risk_spectrum
6    64
5    12
4     7
7     6
1     1
Name: count, dtype: int64

# No RMF SSF

In [10]:
SCB_amc_no_rmf_ssf

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
12,M0003_2554,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
20,M0004_2564,NaN,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
25,M0005_2556,NaN,"FIF,SPF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
35,M0006_2556,NaN,"FIF,SPF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
36,M0006_2558,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
...,...,...,...,...,...,...
2762,M1086_2557,NaN,"FIF,SPF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2774,M1126_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2775,M1127_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2782,M1179_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2796,M1233_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

ดึง api มาเขียน risk_spectrum

In [36]:
tmp_SCB_amc_no_rmf_ssf = SCB_amc_no_rmf_ssf.reset_index()
tmp_SCB_amc_no_rmf_ssf = tmp_SCB_amc_no_rmf_ssf.drop(columns=['index'])
tmp_SCB_amc_no_rmf_ssf

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,M0003_2554,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1,M0004_2564,5,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2,M0005_2556,NaN,"FIF,SPF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
3,M0006_2556,NaN,"FIF,SPF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
4,M0006_2558,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
...,...,...,...,...,...,...
1168,M1086_2557,NaN,"FIF,SPF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1169,M1126_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1170,M1127_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1171,M1179_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1172,M1233_2557,NaN,SPF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

In [48]:
import re
import pdfbox
import os
from IPython.display import clear_output
p = pdfbox.PDFBox()
not_screenable = []
max_len = len(tmp_SCB_amc_no_rmf_ssf)
for index, row in tmp_SCB_amc_no_rmf_ssf.iterrows():
        response = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/{row["proj_id"]}/URLs',headers=headers2)
        res_text = json.loads(response.text)
        res_pdf = requests.get(res_text['url_factsheet'])
        with open(f"tmp/tmp.pdf", 'wb') as pdf_file:
                pdf_file.write(res_pdf.content)
        try:
                print(str(index+1) + ' of ' + str(max) +' '+ str(round(((index+1)/max_len)*100,2))+' % Completed' )
                if os.path.getsize("tmp/tmp.pdf") < 216:
                        raise Exception("File not found ::") 
                p.extract_text(f'tmp/tmp.pdf')
                with open(f'tmp/tmp.txt', 'r',  encoding="utf8") as file:
                        data = file.read()
                match = re.search(r'(\S+)\s*:\s*เสี่ยง', data)
                if match:
                        number_before_string = match.group(1)
                        tmp_SCB_amc_no_rmf_ssf.at[index, 'risk_spectrum'] = number_before_string
                else:
                        print("Pattern not found on "+ row["proj_id"])
                clear_output(wait=True)
        except Exception as e:
                print(str(e) +' Error found on '+ row['proj_id'])
                not_screenable.append(row["proj_id"])

1171 of 1173 99.83 % Completed
File not found :: Error found on M1127_2557
1172 of 1173 99.91 % Completed
File not found :: Error found on M1179_2557
1173 of 1173 100.0 % Completed
Pattern not found on M1233_2557

In [49]:
tmp_SCB_amc_no_rmf_ssf['risk_spectrum'].value_counts()

risk_spectrum
3    63
6    27
5    14
7     4
1     2
Name: count, dtype: int64

In [57]:
SCB_amc_no_rmf_ssf_filtered = tmp_SCB_amc_no_rmf_ssf.dropna()
SCB_amc_no_rmf_ssf_filtered

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
1,M0004_2564,5,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
19,M0015_2564,6,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
29,M0024_2560,6,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
31,M0026_2539,6,IND,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
32,M0026_2551,6,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
...,...,...,...,...,...,...
1118,M0936_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1119,M0937_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1121,M0938_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1123,M0939_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1126,M0940_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

In [ ]:
SCB_amc_no_rmf_ssf_filtered = SCB_amc_no_rmf_ssf_filtered.reset_index()

In [ ]:
SCB_amc_no_rmf_ssf_filtered = SCB_amc_no_rmf_ssf_filtered.drop(columns=['level_0','index'])

In [65]:
SCB_amc_no_rmf_ssf_filtered

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,M0004_2564,5,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1,M0015_2564,6,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2,M0024_2560,6,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
3,M0026_2539,6,IND,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
4,M0026_2551,6,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
...,...,...,...,...,...,...
105,M0936_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
106,M0937_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
107,M0938_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
108,M0939_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
109,M0940_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

In [66]:
SCB_amc_no_rmf_ssf_filtered.to_csv('SCB_amc_data/SCB_amc_filter_w_risk_spectrum_no_nan.csv', encoding='utf8')

# KBANK

In [3]:
# C0000000021 unique ID of KBANK
import time
import csv
from IPython.display import clear_output
header = ['proj_id','risk_spectrum','spec_code','proj_retail_type']
list_risk = []
response = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/amc/C0000000021', headers = headers2)
obj_dict = json.loads(response.text)
filename = f'amc_data/KBANK_amc_data/KBANK_AMC_DATA.csv'
max = len(obj_dict)
with open(filename,'w',newline = '') as f_out:    
    f_out = csv.writer(f_out,quoting=csv.QUOTE_ALL)
    f_out.writerow(header)
    count = 1
    for x in obj_dict:
            suit_tmp = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/{x["proj_id"]}/suitability', headers=headers2)
            spec_tmp = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/{x["proj_id"]}/specification', headers=headers2)
            type_tmp = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/{x["proj_id"]}/project_type', headers=headers2)
            time.sleep(0.1)
            tmp_data = {}
            suit_json = {}
            spec_json = {}
            type_json = {}
            print(str(count)+' of '+str(max))
            try:
                # suit
                suit_json = json.loads(suit_tmp.text)
                tmp_data['proj_id'] = x['proj_id']
                tmp_data['risk_spectrum'] = suit_json['risk_spectrum']
            except Exception as e1:
                pass
            try:
                # spec
                spec_json = json.loads(spec_tmp.text)
                tmp_data['proj_id'] = x['proj_id']
                tmp_data['spec_code'] = ','.join(y['spec_code'] for y in spec_json)
            except Exception as e2:
                pass
            try:
                # type
                type_json = json.loads(type_tmp.text)
                tmp_data['proj_id'] = x['proj_id']
                tmp_data['proj_retail_type'] = type_json['proj_retail_type']
            except Exception as e3:
                pass
            if not tmp_data == {}:
                f_out.writerow([tmp_data.get('proj_id'), tmp_data.get('risk_spectrum'), tmp_data.get('spec_code'), tmp_data.get('proj_retail_type')])
            count+=1
            clear_output(wait=True)

2038 of 2038

In [9]:
import pandas as pd
KBANK_amc_data = pd.DataFrame(columns = ['proj_id','risk_spectrum','spec_code','amc','name_th','proj_retail_type'])
file = pd.read_csv(f'amc_data/KBANK_amc_data/KBANK_AMC_DATA.csv')
file['amc'] =  'C0000000021'
file['name_th'] = 'บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด'
KBANK_amc_data = pd.concat([KBANK_amc_data,file])
KBANK_amc_data_clean = KBANK_amc_data.dropna(subset=['spec_code','proj_retail_type'])
KBANK_amc_data_clean.drop(KBANK_amc_data_clean[KBANK_amc_data_clean['proj_retail_type'] != 'R'].index, inplace = True)
KBANK_amc_data_clean

C:\Users\User\AppData\Local\Temp\ipykernel_68660\772646567.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  KBANK_amc_data_clean.drop(KBANK_amc_data_clean[KBANK_amc_data_clean['proj_retail_type'] != 'R'].index, inplace = True)

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,M0000_2553,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
4,M0004_2555,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
7,M0006_2557,NaN,"CPF,SPF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
9,M0007_2553,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
10,M0007_2554,NaN,"GF,SNF,SPF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
...,...,...,...,...,...,...
2025,M1198_2557,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
2026,M1209_2557,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
2029,M1224_2557,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
2035,M1261_2557,NaN,"FED,IND",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
2036,M1262_2557,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R

In [10]:
KBANK_amc_rmf_ssf = KBANK_amc_data_clean[KBANK_amc_data_clean['spec_code'].str.contains('RMF', case=False, na=False) | KBANK_amc_data_clean['spec_code'].str.contains('SSF', case=False, na=False)]
KBANK_amc_no_rmf_ssf = KBANK_amc_data_clean[~(KBANK_amc_data_clean['spec_code'].str.contains('RMF', case=False, na=False) | KBANK_amc_data_clean['spec_code'].str.contains('SSF', case=False, na=False))]

In [11]:
tmp_KBANK_amc_rmf_ssf = KBANK_amc_rmf_ssf.reset_index()
tmp_KBANK_amc_rmf_ssf = tmp_KBANK_amc_rmf_ssf.drop(columns=['index'])
tmp_KBANK_amc_rmf_ssf

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,M0045_2565,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
1,M0054_2560,NaN,SSF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
2,M0061_2544,NaN,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
3,M0062_2544,NaN,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
4,M0063_2544,NaN,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
5,M0064_2544,NaN,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
6,M0065_2544,NaN,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
7,M0131_2562,NaN,"FED,SSF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
8,M0159_2549,NaN,SSF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
9,M0159_2555,NaN,"FED,SSF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
10,M0161_2563,NaN,SSF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
11,M0192_2559,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
12,M0217_2558,NaN,"FED,SSF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
13,M0377_2556,NaN,SSF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
14,M0405_2549,NaN,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
15,M0410_2558,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
16,M0433_2558,NaN,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
17,M0468_2563,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
18,M0470_2563,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
19,M0511_2565,NaN,"FED,SSF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
20,M0512_2563,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
21,M0527_2560,NaN,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
22,M0529_2563,NaN,"FF,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
23,M0545_2563,NaN,"CIV,FF,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
24,M0552_2565,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
25,M0573_2566,NaN,"FF,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
26,M0579_2552,NaN,"FED,SSF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
27,M0580_2566,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
28,M0596_2562,NaN,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
29,M0596_2566,NaN,"FF,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
30,M0599_2566,NaN,"FED,RMF,SE",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
31,M0608_2557,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
32,M0679_2557,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
33,M0714_2552,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
34,M0738_2556,NaN,"IND,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
35,M0861_2553,NaN,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R

In [12]:
tmp_KBANK_amc_no_rmf_ssf = KBANK_amc_no_rmf_ssf.reset_index()
tmp_KBANK_amc_no_rmf_ssf = tmp_KBANK_amc_no_rmf_ssf.drop(columns=['index'])
tmp_KBANK_amc_no_rmf_ssf

,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,M0000_2553,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
1,M0004_2555,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
2,M0006_2557,NaN,"CPF,SPF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
3,M0007_2553,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
4,M0007_2554,NaN,"GF,SNF,SPF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
...,...,...,...,...,...,...
953,M1198_2557,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
954,M1209_2557,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
955,M1224_2557,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
956,M1261_2557,NaN,"FED,IND",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
957,M1262_2557,NaN,SPF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R

In [23]:
import re
import os
import math
from IPython.display import clear_output
from pdf2image import convert_from_path
error_list = []
max_len = len(tmp_KBANK_amc_rmf_ssf)
left = 1730
top = 540
right = 2350
bottom = 610
for index, row in tmp_KBANK_amc_rmf_ssf.iterrows():
        response = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/{row["proj_id"]}/URLs',headers=headers2)
        res_text = json.loads(response.text)
        res_pdf = requests.get(res_text['url_factsheet'])
        with open(f"tmp/tmp.pdf", 'wb') as pdf_file:
                pdf_file.write(res_pdf.content)
        try:
                print(str(index+1) + ' of ' + str(max_len) +' '+ str(round(((index+1)/max_len)*100,2))+' % Completed' )
                images = convert_from_path('tmp/tmp.pdf', 300)
                images[0].save('page'+ str(0) +'.jpg', 'JPEG')
                from PIL import Image
                img = Image.open(r"./page0.jpg") 
                img_res = img.crop((left, top, right, bottom)) 
                img_res.save('./tmp/tmp.jpg')
                img = Image.open('./tmp/tmp.jpg')
                pixels = img.load()
                width, height = img.size
                result_col = 0
                count = 0
                is_black = False
                pillar_count = 0
                for col in range(width):
                        if (0 <= pixels[col,56][-1] <= 10):
                                is_black = True
                                count+=1
                        elif is_black == True:
                                is_black = False
                                pillar_count += 1
                        if (150 <= pixels[col,56][-1] <= 165):
                                result_col = col
                                break
                tmp_KBANK_amc_rmf_ssf.at[index, 'risk_spectrum'] = math.ceil(pillar_count/2)
                print(math.ceil(pillar_count/2))
                clear_output(wait=True)
        except Exception as e:
                print(str(e) +' Error found on '+ row['proj_id'])
                error_list.append(row["proj_id"])
#ดีง pdf และจับความเสี่ยง

36 of 36 100.0 % Completed
5

In [25]:
tmp_KBANK_amc_rmf_ssf['risk_spectrum'].value_counts()

risk_spectrum
6    21
5     7
4     4
8     2
3     1
7     1
Name: count, dtype: int64

In [26]:
tmp_KBANK_amc_rmf_ssf.to_csv('./amc_data/KBANK_AMC_DATA/KBANK_filter_amc_rmf_ssf.csv', encoding='utf8')

# TODO cancel_date from
./amc_data/SCB_amc_data/SCB_amc_filter_w_risk_spectrum_no_nan.csv <br>
./amc_data/SCB_amc_data/SCB_amc_rmf_ssf_filter_w_risk_spectrum_no_nan.csv <br>
./amc_data/KBANK_amc_data/KBANK_filter_amc_rmf_ssf.csv

In [15]:
df_SCB = pd.read_csv("./amc_data/SCB_amc_data/SCB_amc_filter_w_risk_spectrum_no_nan.csv")

In [16]:
df_SCB

,Unnamed: 0,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,0,M0004_2564,5,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1,1,M0015_2564,6,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2,2,M0024_2560,6,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
3,3,M0026_2539,6,IND,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
4,4,M0026_2551,6,FED,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
...,...,...,...,...,...,...,...
105,105,M0936_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
106,106,M0937_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
107,107,M0938_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
108,108,M0939_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
109,109,M0940_2566,3,CRF,C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

In [18]:
df_scb_sf = pd.read_csv("./amc_data/SCB_amc_data/SCB_amc_rmf_ssf_filter_w_risk_spectrum_no_nan.csv")
df_scb_sf

,Unnamed: 0,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,0,M0005_2558,6,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
1,1,M0005_2565,5,"FF,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
2,2,M0017_2565,6,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
3,3,M0049_2565,6,"FED,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
4,4,M0059_2564,6,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
...,...,...,...,...,...,...,...
85,91,M0828_2554,5,"FF,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
86,93,M0866_2554,4,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
87,94,M0874_2554,5,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
88,95,M0933_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
89,96,M0935_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

In [19]:
df_kbank_sf = pd.read_csv("./amc_data/KBANK_amc_data/KBANK_filter_amc_rmf_ssf.csv")
df_kbank_sf

,Unnamed: 0,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,0,M0045_2565,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
1,1,M0054_2560,4,SSF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
2,2,M0061_2544,6,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
3,3,M0062_2544,5,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
4,4,M0063_2544,4,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
5,5,M0064_2544,3,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
6,6,M0065_2544,4,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
7,7,M0131_2562,6,"FED,SSF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
8,8,M0159_2549,6,SSF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
9,9,M0159_2555,6,"FED,SSF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
10,10,M0161_2563,6,SSF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
11,11,M0192_2559,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
12,12,M0217_2558,5,"FED,SSF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
13,13,M0377_2556,4,SSF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
14,14,M0405_2549,6,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
15,15,M0410_2558,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
16,16,M0433_2558,6,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
17,17,M0468_2563,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
18,18,M0470_2563,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
19,19,M0511_2565,6,"FED,SSF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
20,20,M0512_2563,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
21,21,M0527_2560,6,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
22,22,M0529_2563,5,"FF,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
23,23,M0545_2563,5,"CIV,FF,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
24,24,M0552_2565,5,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
25,25,M0573_2566,5,"FF,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
26,26,M0579_2552,6,"FED,SSF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
27,27,M0580_2566,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
28,28,M0596_2562,8,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
29,29,M0596_2566,6,"FF,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
30,30,M0599_2566,7,"FED,RMF,SE",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
31,31,M0608_2557,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
32,32,M0679_2557,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
33,33,M0714_2552,8,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
34,34,M0738_2556,6,"IND,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
35,35,M0861_2553,5,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R

In [21]:
df_sum_sf = pd.concat([df_kbank_sf,df_scb_sf])

In [22]:
df_sum_sf

,Unnamed: 0,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,0,M0045_2565,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
1,1,M0054_2560,4,SSF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
2,2,M0061_2544,6,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
3,3,M0062_2544,5,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
4,4,M0063_2544,4,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
...,...,...,...,...,...,...,...
85,91,M0828_2554,5,"FF,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
86,93,M0866_2554,4,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
87,94,M0874_2554,5,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
88,95,M0933_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
89,96,M0935_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

In [25]:
df_sum_df1 = df_sum_sf.reset_index(drop = True)
df_sum_df1

,Unnamed: 0,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
0,0,M0045_2565,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
1,1,M0054_2560,4,SSF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
2,2,M0061_2544,6,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
3,3,M0062_2544,5,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
4,4,M0063_2544,4,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
...,...,...,...,...,...,...,...
121,91,M0828_2554,5,"FF,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
122,93,M0866_2554,4,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
123,94,M0874_2554,5,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
124,95,M0933_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R
125,96,M0935_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R

In [27]:
df_sum_df1["risk_spectrum"].value_counts()

risk_spectrum
6    85
5    19
4    11
7     7
8     2
3     1
1     1
Name: count, dtype: int64

In [30]:
df_sum_df1[df_sum_df1["risk_spectrum"] == 8]

,Unnamed: 0,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type
28,28,M0596_2562,8,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R
33,33,M0714_2552,8,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R

In [31]:
response = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/amc/C0000000021',headers=headers2)
amc_name = json.loads(response.text)
kbank = pd.DataFrame(amc_name)
kbank

,proj_id,regis_id,regis_date,cancel_date,proj_name_th,proj_name_en,proj_abbr_name,fund_status,unique_id,permit_us_investment,invest_country_flag,last_upd_date
0,M0000_2553,611_2552,2009-12-30,2010-04-02,กองทุนเปิดเค ตราสารหนี้ 3 เดือน บี,K Fixed Income 3 Months B Fund,KFI3MB,LI,C0000000021,None,3,2024-02-02T07:05:48.36
1,M0001_2558,MF0013_2558,2015-01-14,2016-01-21,กองทุนเปิดเค เอ็นแฮนซท์ ตราสารหนี้ต่างประเทศ 1...,K Enhanced Foreign Fixed Income 1 Year AD Fund,KEFF1YAD,LI,C0000000021,None,1,2024-02-02T07:05:48.36
2,M0003_2558,MF0012_2558,2015-01-14,2015-04-23,กองทุนเปิดเค เอ็นแฮนซท์ ตราสารหนี้ 3 เดือน K,K Enhanced Fixed Income 3 Months K Fund,KEFI3MK,LI,C0000000021,None,2,2024-02-02T07:05:48.36
3,M0003_2563,None,-,-,กองทุนเปิดเค ตราสารหนี้ต่างประเทศ 6 เดือน HX,K Foreign Fixed Income 6 Months HX Fund,KFF6MHX,EX,C0000000021,None,1,2024-02-02T07:05:48.36
4,M0004_2555,MF0020_2555,2012-01-18,2012-07-20,กองทุนเปิดเค ตราสารหนี้ 6 เดือน เอเจ,K Fixed Income 6 Months AJ Fund,KFI6MAJ,LI,C0000000021,None,2,2024-02-02T07:05:48.36
...,...,...,...,...,...,...,...,...,...,...,...,...
2033,M1240_2557,MF0871_2557,2014-12-26,2015-07-08,กองทุนเปิดเค เอ็นแฮนซท์ ตราสารหนี้ 6 เดือน F,K Enhanced Fixed Income 6 Months F Fund,KEFI6MF,LI,C0000000021,None,2,2024-02-02T07:05:48.36
2034,M1248_2557,None,-,-,กองทุนเปิดเค เอ็นแฮนซท์ ตราสารหนี้ต่างประเทศ พ...,K Enhanced Foreign Fixed Income Plus 3 Months ...,KEFFP3MA,EX,C0000000021,None,1,2024-02-02T07:05:48.36
2035,M1261_2557,MF0464_2558,2015-09-08,-,กองทุนเปิดเค ดัชนีหุ้นจีน,K Chinese Equity Index Fund,K-CHX,RG,C0000000021,None,1,2024-02-02T07:05:48.36
2036,M1262_2557,MF0011_2558,2015-01-14,2015-07-23,กองทุนเปิดเค ตราสารหนี้ 6 เดือน CO,K Fixed Income 6 Months CO Fund,KFI6MCO,LI,C0000000021,None,2,2024-02-02T07:05:48.36
2037,M1263_2557,MF0010_2558,2015-01-14,2015-07-23,กองทุนเปิดเค เอ็นแฮนซท์ ตราสารหนี้ 6 เดือน G,K Enhanced Fixed Income 6 Months G Fund,KEFI6MG,LI,C0000000021,None,2,2024-02-02T07:05:48.36

In [32]:
response = requests.get(f'https://api.sec.or.th/FundFactsheet/fund/amc/C0000000239',headers=headers2)
amc_name = json.loads(response.text)
scb = pd.DataFrame(amc_name)
scb

,proj_id,regis_id,regis_date,cancel_date,proj_name_th,proj_name_en,proj_abbr_name,fund_status,unique_id,permit_us_investment,invest_country_flag,last_upd_date
0,M0001_2538,046_2538,1995-11-17,2004-04-09,กองทุนเปิดไทยพาณิชย์ตราสารหนี้,SCB FIXED INCOME OPEN END FUND,SCBFI,CA,C0000000239,None,None,2024-02-02T07:05:48.36
1,M0001_2545,None,-,-,กองทุนเปิดไทยพาณิชย์เฉพาะเจาะจง 4,SCB SPECIFIC 4 OPEN END FUND,SCBSOF 4,EX,C0000000239,None,None,2024-02-02T07:05:48.36
2,M0001_2549,008_2549,2006-01-25,2015-01-28,กองทุนเปิดไทยพาณิชย์พันธบัตรรัฐบาล 1/12,SCB GOVERNMENT BOND 1/12 OPEN END FUND,SCBGB1/12,LI,C0000000239,None,3,2024-02-02T07:05:48.36
3,M0001_2559,MF0004_2559,2016-01-12,2016-04-22,กองทุนเปิดไทยพาณิชย์ตราสารหนี้ เอไอ 3M12,SCB FIXED INCOME ACCREDITED INVESTORS FUND 3M12,SCBAI3M12,LI,C0000000239,None,2,2024-02-02T07:05:48.36
4,M0002_2540,003_2541,1998-04-01,2003-03-31,ไทยพาณิชย์พันธบัตรรัฐบาล,SCB GOVERNMENT BOND OPEN END FUND,SCBGB,LI,C0000000239,None,None,2024-02-02T07:05:48.36
...,...,...,...,...,...,...,...,...,...,...,...,...
2796,M1233_2557,MF0861_2557,2014-12-23,2015-02-06,กองทุนเปิดไทยพาณิชย์ ทริกเกอร์ 3% พลัส 3% ฟันด...,SCB TRIGGER 3% PLUS 3% FUND A,SCBTG3P3A,LI,C0000000239,None,3,2024-02-02T07:05:48.36
2797,M1235_2557,MF0023_2558,2015-01-20,2015-05-01,กองทุนเปิดไทยพาณิชย์ตราสารหนี้ต่างประเทศ เอเอส...,SCB FOREIGN FIXED INCOME ACCREDITED INVESTORS ...,SCBASF3M59,LI,C0000000239,None,1,2024-02-02T07:05:48.36
2798,M1236_2557,MF0004_2558,2015-01-13,2015-07-24,กองทุนเปิดไทยพาณิชย์ตราสารหนี้ต่างประเทศ เอเอส...,SCB FOREIGN FIXED INCOME ACCREDITED INVESTORS ...,SCBASF6M52,LI,C0000000239,None,1,2024-02-02T07:05:48.36
2799,M1237_2557,MF0066_2558,2015-02-10,2016-02-19,กองทุนเปิดไทยพาณิชย์ตราสารหนี้ต่างประเทศ เอเอส...,SCB FOREIGN FIXED INCOME ACCREDITED INVESTORS ...,SCBASF1Y18,LI,C0000000239,None,1,2024-02-02T07:05:48.36
2800,M1246_2557,MF0024_2558,2015-01-20,2015-07-30,กองทุนเปิดไทยพาณิชย์ตราสารหนี้ต่างประเทศ เอเอส...,SCB FOREIGN FIXED INCOME ACCREDITED INVESTORS ...,SCBASF6M53,LI,C0000000239,None,1,2024-02-02T07:05:48.36

In [39]:
sum_scb_kbank = pd.concat([kbank,scb])
sum_scb_kbank1 = sum_scb_kbank.reset_index(drop = True)
sum_scb_kbank2 = sum_scb_kbank1[["proj_id","fund_status","cancel_date"]]
sum_scb_kbank2[sum_scb_kbank2["cancel_date"]=="-"]

         proj_id fund_status cancel_date
3     M0003_2563          EX           -
5     M0004_2563          EX           -
12    M0008_2537          RG           -
17    M0008_2567          RG           -
18    M0009_2543          RG           -
...          ...         ...         ...
4820  M1179_2557          EX           -
4824  M1192_2557          EX           -
4825  M1193_2557          EX           -
4829  M1213_2557          EX           -
4830  M1215_2557          EX           -

[924 rows x 3 columns]

In [54]:
ssf_mapping = pd.merge(df_sum_df1, sum_scb_kbank2, on='proj_id')

In [60]:
ssf_mapping[ssf_mapping["cancel_date"]!="-"]

,Unnamed: 0,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type,fund_status,cancel_date
117,86,M0721_2565,1,"FED,MM,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R,CA,2023-03-01

In [61]:
ssf_mapping1 = ssf_mapping

In [62]:
ssf_mapping_filtered = ssf_mapping1.drop(ssf_mapping1[ssf_mapping["cancel_date"]!="-"].index)

In [63]:
ssf_mapping_filtered

,Unnamed: 0,proj_id,risk_spectrum,spec_code,amc,name_th,proj_retail_type,fund_status,cancel_date
0,0,M0045_2565,6,"FED,RMF",C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R,RG,-
1,1,M0054_2560,4,SSF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R,RG,-
2,2,M0061_2544,6,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R,RG,-
3,3,M0062_2544,5,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R,RG,-
4,4,M0063_2544,4,RMF,C0000000021,บริษัท หลักทรัพย์จัดการกองทุนกสิกรไทย จำกัด,R,RG,-
...,...,...,...,...,...,...,...,...,...
121,91,M0828_2554,5,"FF,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R,RG,-
122,93,M0866_2554,4,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R,RG,-
123,94,M0874_2554,5,"FED,SSF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R,RG,-
124,95,M0933_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R,RG,-
125,96,M0935_2554,5,"FF,RMF",C0000000239,บริษัท หลักทรัพย์จัดการกองทุนไทยพาณิชย์ จำกัด,R,RG,-

In [148]:

df_21 = pd.read_csv("./spec_suit/C0000000709.csv")
df_21[df_21["risk_spectrum"].notna()]["risk_spectrum"].value_counts()
df_21[df_21["risk_spectrum"]=="RS2"]
#C0000000709 = rs2 1

        proj_id risk_spectrum spec_code
140  M0177_2549           RS2        MM

In [143]:
df = pd.DataFrame(columns=['A', 'B'])

# Example data to append
data_to_append = [{'A': 1, 'B': 2},
                  {'A': 3, 'B': 4},
                  {'A': 5, 'B': 6}]

# Append data to DataFrame row by row using a for loop
for row in data_to_append:
    df = df._append(row, ignore_index=True)

print(df)

   A  B
0  1  2
1  3  4
2  5  6

In [126]:
df_RS2 = pd.DataFrame(columns=df_21.columns)
df_RS2._append

In [154]:
import os
directory = "./spec_suit/"
list_rs2 = []
df_RS2 = pd.DataFrame(columns=df_21.columns)
for filename in os.listdir(directory):
    # Check if the file is a regular file
    if os.path.isfile(os.path.join(directory, filename)):
        df_21 = pd.read_csv(f"./spec_suit/{filename}")
        df_Rs2_temp = df_21[df_21["risk_spectrum"]=="RS2"]
        #df_RS2 = pd.concat([df_RS2, df_Rs2_temp])
        df_RS2 = df_RS2._append(df_Rs2_temp)
        print(df_21)

         proj_id risk_spectrum spec_code
0     M0000_2553           NaN       SPF
1     M0001_2558           NaN   FIF,SPF
2     M0003_2558           NaN       SPF
3     M0003_2563           NaN       NaN
4     M0004_2555           NaN       SPF
...          ...           ...       ...
1706  M1240_2557           NaN       SPF
1707  M1248_2557           NaN   FIF,SPF
1708  M1261_2557           NaN   FED,IND
1709  M1262_2557           NaN       SPF
1710  M1263_2557           NaN       SPF

[1711 rows x 3 columns]
        proj_id risk_spectrum   spec_code
0    M0000_2552           NaN         SSF
1    M0001_2524           NaN         OTH
2    M0001_2531           NaN         NaN
3    M0001_2550           NaN         SPF
4    M0002_2530           NaN         NaN
..          ...           ...         ...
388  M0997_2553           NaN          MM
389  M1025_2553           NaN     FIF,SPF
390  M1031_2553           NaN         NaN
391  M1033_2553           NaN  FIF,GF,SPF
392  M1105_2557           NaN         SPF

[393 rows x 3 columns]
       proj_id  risk_spectrum   spec_code
0   M0063_2552            NaN         SPF
1   M0073_2551            NaN         SPF
2   M0103_2551            NaN         CPF
3   M0104_2551            NaN         CPF
4   M0142_2551            NaN         SPF
5   M0143_2551            NaN         SPF
6   M0171_2552            NaN         SPF
7   M0173_2551            NaN     FIF,SPF
8   M0181_2552            NaN     FIF,SPF
9   M0189_2552            NaN         SPF
10  M0221_2551            NaN     FIF,SPF
11  M0222_2551            NaN     FIF,SPF
12  M0223_2551            NaN         FIF
13  M0236_2552            NaN     FIF,SPF
14  M0265_2551            NaN     FIF,SPF
15  M0266_2551            NaN     FIF,SPF
16  M0268_2551            NaN     FIF,SPF
17  M0308_2551            NaN  FED,FF,FIF
18  M0383_2550            NaN         SPF
19  M0464_2550            NaN  FED,FF,FIF
20  M0470_2551            NaN         CPF
21  M0479_2551            NaN         CPF
22  M0488_2551            NaN         CPF
23  M0508_2550            NaN  FED,FF,FIF
24  M0509_2550            NaN  FED,FF,FIF
25  M0524_2551            NaN  FED,FF,FIF
26  M0632_2551            NaN         SPF
27  M0704_2551            NaN          MM
28  M0825_2554            NaN      FIF,GF
29  M0965_2554            NaN          GF
        proj_id risk_spectrum spec_code
0    M0007_2551           NaN   FIF,SPF
1    M0008_2551           NaN   FIF,SPF
2    M0010_2551           NaN   FIF,SPF
3    M0011_2553           RS4       NaN
4    M0013_2551           NaN   FIF,SPF
..          ...           ...       ...
216  M0978_2556           NaN       FIF
217  M1098_2557           NaN       FIF
218  M1135_2557           NaN       FIF
219  M1156_2557           NaN       FIF
220  M1243_2557           NaN       FIF

[221 rows x 3 columns]
         proj_id risk_spectrum spec_code
0     M0002_2549           RS3       NaN
1     M0002_2563           NaN       NaN
2     M0003_2539           NaN       NaN
3     M0003_2554           NaN       SPF
4     M0003_2562           RS4       NaN
...          ...           ...       ...
2087  M1233_2557           NaN       SPF
2088  M1235_2557           NaN   FIF,SPF
2089  M1236_2557           NaN   FIF,SPF
2090  M1237_2557           NaN   FIF,SPF
2091  M1246_2557           NaN   FIF,SPF

[2092 rows x 3 columns]
       proj_id  risk_spectrum spec_code
0   M0025_2565            NaN   FED,SSF
1   M0027_2541            NaN        MM
2   M0035_2547            NaN       NaN
3   M0041_2554            NaN       FED
4   M0045_2564            NaN   FED,SSF
5   M0065_2549            NaN       FED
6   M0066_2546            NaN       NaN
7   M0071_2546            NaN       NaN
8   M0117_2564            NaN   FED,SSF
9   M0140_2545            NaN       RMF
10  M0141_2545            NaN       RMF
11  M0157_2550            NaN       FED
12  M0187_2563            NaN       SSF
13  M0250_2547            NaN       SPF
14  M0250_2564            NaN   FED,SSF
15  M0250_2565            NaN   FED,SSF
16  M0256_2550            NaN       FED
17  M0285_2546            NaN       NaN
18  M0303_2564            NaN   FED,SSF
19  M0315_2561            NaN       FED
20  M0348_2555            NaN       SSF
21  M0363_2549            NaN       FED
22  M0401_2552            NaN   FED,SSF
23  M0413_2548            NaN       SSF
24  M0458_2557            NaN       FED
25  M0470_2562            NaN        MM
26  M0487_2562            NaN       NaN
27  M0488_2562            NaN       NaN
28  M0529_2559            NaN       LTF
29  M0532_2556            NaN       FED
30  M0536_2564            NaN   FED,SSF
31  M0562_2558            NaN   FED,SSF
32  M0569_2565            NaN       RMF
33  M0570_2565            NaN   FED,RMF
34  M0581_2566            NaN   FED,SSF
35  M0582_2548            NaN   FED,SSF
36  M0584_2553            NaN       FED
37  M0698_2547            NaN       LTF
38  M0774_2554            NaN   FED,RMF
        proj_id risk_spectrum spec_code
0    M0001_2563           NaN       FED
1    M0004_2535           NaN       NaN
2    M0004_2556           NaN   FED,RMF
3    M0004_2557           NaN       FIF
4    M0005_2535           NaN       NaN
..          ...           ...       ...
424  M1087_2557           NaN       FIF
425  M1151_2557           NaN        FF
426  M1183_2557           NaN    FED,SE
427  M1230_2557           NaN       FIF
428  M1244_2557           NaN       FED

[429 rows x 3 columns]
        proj_id risk_spectrum spec_code
0    M0001_2565           NaN       NaN
1    M0003_2551           NaN   FIF,SPF
2    M0003_2559           NaN   FIF,SPF
3    M0004_2551           NaN   FIF,SPF
4    M0004_2553           NaN       SPF
..          ...           ...       ...
719  M1149_2557           NaN       SPF
720  M1166_2557           NaN       SPF
721  M1177_2557           NaN       SPF
722  M1189_2557           NaN       SPF
723  M1252_2557           NaN       SPF

[724 rows x 3 columns]
         proj_id risk_spectrum spec_code
0     M0002_2553           NaN   FIF,SPF
1     M0002_2554           NaN   FIF,SPF
2     M0002_2557           NaN       SPF
3     M0004_2545           NaN       NaN
4     M0007_2563           NaN       NaN
...          ...           ...       ...
1018  M1204_2557           NaN       SPF
1019  M1216_2557           NaN   FIF,SPF
1020  M1231_2557           NaN       SPF
1021  M1250_2557           NaN   FED,SSF
1022  M1256_2557           NaN       SPF

[1023 rows x 3 columns]
        proj_id risk_spectrum spec_code
0    M0001_2540           NaN       NaN
1    M0003_2540           NaN        CF
2    M0015_2536           NaN       NaN
3    M0016_2536           NaN       NaN
4    M0016_2560           NaN        SE
..          ...           ...       ...
164  M0909_2556           NaN   FIF,SPF
165  M0921_2555           NaN   OTH,SPF
166  M0932_2553           NaN       SPF
167  M1238_2557           NaN   FIF,SPF
168  M1247_2557           NaN       SPF

[169 rows x 3 columns]
        proj_id risk_spectrum spec_code
0    M0001_2536           RS6       NaN
1    M0002_2560           NaN   FED,SSF
2    M0005_2563           NaN       FED
3    M0010_2549           NaN   FED,FIF
4    M0010_2557           NaN   FIF,SPF
..          ...           ...       ...
462  M1175_2557           NaN   FIF,SPF
463  M1199_2557           RS5       FED
464  M1232_2557           RS5       NaN
465  M1245_2557           NaN       FIF
466  M1253_2557           NaN       FIF

[467 rows x 3 columns]
        proj_id risk_spectrum spec_code
0    M0003_2555           NaN       SPF
1    M0003_2557           NaN       SPF
2    M0004_2554           NaN       SPF
3    M0009_2553           NaN       FED
4    M0009_2556           NaN       SPF
..          ...           ...       ...
630  M1167_2557           NaN       SPF
631  M1176_2557           NaN       SPF
632  M1196_2557           NaN       SPF
633  M1208_2557           NaN       SPF
634  M1257_2557           NaN       FED

[635 rows x 3 columns]
        proj_id risk_spectrum spec_code
0    M0001_2551           NaN       FIF
1    M0002_2552           NaN       SPF
2    M0003_2549           NaN       CPF
3    M0003_2552           NaN       CPF
4    M0005_2549           NaN       CPF
..          ...           ...       ...
673  M1241_2557           NaN       FIF
674  M1242_2557           RS5       NaN
675  M1249_2557           NaN       SPF
676  M1254_2557           NaN       SPF
677  M1258_2557           NaN       SPF

[678 rows x 3 columns]
      proj_id risk_spectrum  spec_code
0  M0262_2560           RS6        NaN
1  M0640_2560           RS6        NaN
       proj_id  risk_spectrum spec_code
0   M0006_2554            NaN   FIF,SPF
1   M0011_2555            NaN       SPF
2   M0036_2554            NaN       SPF
3   M0058_2554            NaN   FIF,SPF
4   M0072_2554            NaN       SPF
..         ...            ...       ...
73  M0909_2553            NaN   FIF,SPF
74  M0937_2553            NaN   FIF,SPF
75  M0941_2554            NaN   FIF,SPF
76  M0978_2553            NaN   FIF,SPF
77  M1032_2553            NaN   FIF,SPF

[78 rows x 3 columns]
        proj_id risk_spectrum spec_code
0    M0003_2553           NaN        FF
1    M0007_2564           NaN       NaN
2    M0010_2550           NaN       SPF
3    M0024_2551           NaN       SPF
4    M0031_2551           NaN   FIF,SPF
..          ...           ...       ...
182  M0955_2556           NaN       FIF
183  M0971_2553           NaN       SPF
184  M0976_2553           NaN       SPF
185  M1002_2555           NaN   FIF,SPF
186  M1202_2557           NaN    FED,SE

[187 rows x 3 columns]
        proj_id risk_spectrum spec_code
0    M0001_2553           NaN       CPF
1    M0001_2561           NaN       NaN
2    M0007_2559           NaN       SPF
3    M0009_2561           NaN   FED,SSF
4    M0011_2552           NaN       SPF
..          ...           ...       ...
370  M0986_2554           NaN       SPF
371  M1000_2553           NaN       SPF
372  M1096_2557           NaN       SPF
373  M1169_2557           NaN       SPF
374  M1255_2557           NaN       SPF

[375 rows x 3 columns]
        proj_id risk_spectrum spec_code
0    M0001_2552           NaN       IND
1    M0004_2558           NaN       SPF
2    M0005_2552           NaN       CPF
3    M0006_2555           NaN       SPF
4    M0006_2561           NaN       FED
..          ...           ...       ...
207  M0976_2556           NaN       FED
208  M1100_2557           NaN       SPF
209  M1142_2557           NaN   FED,RMF
210  M1172_2557           NaN       SPF
211  M1218_2557           NaN       NaN

[212 rows x 3 columns]
       proj_id risk_spectrum spec_code
0   M0006_2552           NaN       SPF
1   M0007_2552           NaN       SPF
2   M0017_2551           NaN        MM
3   M0020_2555           NaN       SPF
4   M0024_2552           NaN        MM
5   M0033_2552           NaN       SPF
6   M0044_2558           NaN       SPF
7   M0046_2564           NaN       NaN
8   M0047_2564           NaN   FED,SSF
9   M0062_2555           NaN       SPF
10  M0094_2564           NaN   FED,SSF
11  M0095_2563           NaN       SSF
12  M0121_2554           NaN       SPF
13  M0161_2555           NaN       SPF
14  M0169_2554           NaN       SPF
15  M0177_2560           RS6       NaN
16  M0198_2553           NaN       SPF
17  M0209_2555           NaN       SPF
18  M0245_2553           NaN       FIF
19  M0254_2552           NaN       SPF
20  M0257_2550           NaN       LTF
21  M0260_2557           NaN       SPF
22  M0265_2555           NaN       SPF
23  M0319_2550           NaN       SPF
24  M0340_2563           NaN       NaN
25  M0359_2552           RS6       RMF
26  M0360_2558           NaN       SPF
27  M0380_2552           NaN       SPF
28  M0438_2551           NaN       RMF
29  M0445_2556           NaN       SPF
30  M0451_2552           NaN       SPF
31  M0457_2553           NaN   FIF,SPF
32  M0460_2554           NaN       SPF
33  M0460_2558           NaN       SPF
34  M0496_2554           NaN       FIF
35  M0522_2563           NaN       NaN
36  M0525_2558           NaN       SPF
37  M0543_2563           NaN       NaN
38  M0592_2563           NaN       NaN
39  M0600_2552           NaN       SPF
40  M0603_2552           NaN       SPF
41  M0604_2553           NaN       SPF
42  M0657_2554           NaN       SPF
43  M0683_2551           NaN       SPF
44  M0693_2553           NaN       SPF
45  M0709_2552           NaN       SPF
46  M0713_2557           NaN       SPF
47  M0765_2553           NaN       SPF
48  M0798_2553           NaN       SPF
49  M0810_2553           NaN       SPF
50  M0843_2553           NaN       SPF
51  M0907_2553           NaN       SPF
52  M0933_2553           NaN       FIF
53  M0991_2553           NaN       SPF
       proj_id  risk_spectrum spec_code
0   M0037_2564            NaN       FED
1   M0087_2563            NaN       NaN
2   M0098_2551            NaN       RMF
3   M0173_2553            NaN       FIF
4   M0244_2550            NaN       LTF
5   M0249_2561            NaN        FF
6   M0281_2550            NaN        MM
7   M0377_2550            NaN       FIF
8   M0382_2563            NaN    FF,RMF
9   M0422_2557            NaN       FIF
10  M0430_2556            NaN       NaN
11  M0528_2550            NaN       SPF
12  M0536_2552            NaN       FED
13  M0557_2551            NaN       RMF
14  M0632_2558            NaN       SPF
       proj_id risk_spectrum spec_code
0   M0027_2559           NaN       FED
1   M0027_2565           NaN   FED,SSF
2   M0043_2561           NaN        SE
3   M0043_2562           NaN       FED
4   M0114_2557           RS6       FED
5   M0125_2553           NaN       FED
6   M0131_2558           NaN       FED
7   M0133_2561           NaN    FED,SE
8   M0202_2561           NaN       FED
9   M0207_2561           NaN       FED
10  M0209_2561           NaN       FED
11  M0225_2550           NaN       FED
12  M0234_2550           NaN   LTF,SSF
13  M0235_2550           NaN       NaN
14  M0284_2550           NaN       SPF
15  M0285_2560           NaN        FF
16  M0318_2551           NaN       FIF
17  M0376_2557           NaN   FED,RMF
18  M0381_2564           NaN       NaN
19  M0390_2550           NaN       FED
20  M0493_2557           NaN    FED,SE
21  M0521_2550           NaN        MM
22  M0537_2561           RS4       NaN
23  M0553_2566           NaN       FED
24  M0554_2555           RS6       FED
25  M0595_2551           NaN       NaN
26  M0596_2551           NaN    FED,FF
27  M0597_2557           NaN       FIF
28  M0721_2551           NaN       RMF
29  M0844_2566           NaN      TESG
30  M0967_2555           NaN       SPF
       proj_id risk_spectrum spec_code
0   M0096_2559           NaN       FED
1   M0159_2558           NaN       FIF
2   M0513_2559           RS6       NaN
3   M0554_2553           NaN        MM
4   M0590_2558           NaN       FIF
5   M0612_2559           RS6       NaN
6   M0665_2557           NaN       SPF
7   M0708_2557           NaN        MM
8   M0750_2557           NaN   ETF,FIF
9   M0751_2557           NaN   ETF,FIF
10  M0752_2557           NaN   ETF,FIF
11  M0753_2557           NaN   ETF,FIF
        proj_id risk_spectrum   spec_code
0    M0016_2565           NaN          MM
1    M0024_2561           NaN         FED
2    M0031_2561           NaN         FED
3    M0050_2565           NaN  FED,SE,SSF
4    M0052_2564           NaN     FED,SSF
..          ...           ...         ...
100  M0885_2555           NaN         RMF
101  M0890_2555           NaN         RMF
102  M0967_2556           NaN         SPF
103  M0988_2555           NaN         SPF
104  M1182_2557           NaN         SPF

[105 rows x 3 columns]
       proj_id  risk_spectrum spec_code
0   M0015_2563            NaN        FF
1   M0016_2563            NaN       FED
2   M0022_2565            NaN       NaN
3   M0037_2563            NaN    FF,RMF
4   M0041_2563            NaN    FF,RMF
5   M0042_2563            NaN    FF,RMF
6   M0050_2558            NaN       ETF
7   M0056_2564            NaN        FF
8   M0057_2564            NaN        FF
9   M0062_2561            NaN       ETF
10  M0064_2561            NaN       ETF
11  M0068_2563            NaN    FF,SSF
12  M0069_2563            NaN    FF,SSF
13  M0070_2563            NaN    FF,SSF
14  M0072_2563            NaN    FF,SSF
15  M0073_2563            NaN    FF,SSF
16  M0096_2562            NaN        FF
17  M0130_2561            NaN       ETF
18  M0136_2566            NaN        FF
19  M0143_2561            NaN       ETF
20  M0144_2561            NaN       ETF
21  M0146_2562            NaN        FF
22  M0147_2562            NaN        FF
23  M0148_2562            NaN        FF
24  M0149_2562            NaN        FF
25  M0158_2565            NaN   FED,RMF
26  M0186_2563            NaN       NaN
27  M0188_2563            NaN        FF
28  M0251_2560            NaN       ETF
29  M0255_2561            NaN       ETF
30  M0259_2560            NaN       ETF
31  M0356_2561            NaN   IND,LTF
32  M0384_2565            NaN        MM
33  M0439_2562            NaN       NaN
34  M0462_2562            NaN       NaN
35  M0477_2563            NaN    FF,RMF
36  M0480_2563            NaN    FF,RMF
37  M0481_2563            NaN    FF,RMF
38  M0482_2563            NaN    FF,RMF
39  M0484_2563            NaN    FF,RMF
40  M0491_2566            NaN       FED
41  M0504_2563            NaN        FF
42  M0581_2563            NaN        FF
43  M0584_2563            NaN       IND
44  M0588_2562            NaN        FF
45  M0590_2562            NaN        FF
46  M0594_2560            NaN       ETF
47  M0619_2562            NaN        FF
48  M0624_2563            NaN        FF
49  M0625_2563            NaN        FF
50  M0626_2563            NaN        FF
51  M0627_2563            NaN        FF
52  M0697_2562            NaN        FF
53  M0698_2562            NaN        FF
54  M0699_2562            NaN       NaN
55  M0700_2562            NaN        FF
56  M0701_2562            NaN        FF
57  M0702_2562            NaN       NaN
       proj_id  risk_spectrum spec_code
0   M0071_2561            NaN       NaN
1   M0155_2565            NaN       SSF
2   M0344_2564            NaN   FED,SSF
3   M0457_2564            NaN       RMF
4   M0478_2564            NaN   FED,SSF
5   M0485_2560            NaN       NaN
6   M0525_2566            NaN   FED,RMF
7   M0532_2559            NaN       NaN
8   M0585_2559            NaN       LTF
9   M0595_2565            NaN       SSF
10  M0596_2559            NaN       RMF
11  M0598_2559            NaN       RMF
12  M0614_2560            NaN       LTF
13  M0616_2560            NaN       RMF
14  M0619_2565            NaN       RMF
15  M0628_2559            NaN    MM,RMF
16  M0669_2559            NaN    MM,SSF
17  M0681_2559            NaN       NaN
18  M0682_2566            NaN       SSF
19  M0683_2559            NaN       SSF
20  M0761_2566            NaN       RMF
21  M0822_2566            NaN      TESG
       proj_id  risk_spectrum   spec_code
0   M0008_2564            NaN         FED
1   M0014_2565            NaN         NaN
2   M0014_2566            NaN         FED
3   M0024_2563            NaN          FF
4   M0027_2563            NaN         FED
5   M0055_2564            NaN         FED
6   M0078_2563            NaN          FF
7   M0104_2564            NaN          FF
8   M0105_2562            NaN          MM
9   M0105_2563            NaN       FF,SE
10  M0110_2565            NaN         NaN
11  M0113_2563            NaN         FED
12  M0137_2562            NaN         NaN
13  M0159_2562            NaN         NaN
14  M0162_2565            NaN         NaN
15  M0169_2565            NaN         FED
16  M0197_2563            NaN         NaN
17  M0203_2562            NaN          FF
18  M0205_2564            NaN         NaN
19  M0210_2563            NaN         NaN
20  M0220_2564            NaN       FF,SE
21  M0246_2562            NaN          FF
22  M0252_2562            NaN      FED,SE

In [155]:
df_RS2

        proj_id risk_spectrum spec_code
140  M0177_2549           RS2        MM